version: '3'

services:
    backend:
        build: ./backend
        environment:
        - NODE_ENV=production
        ports:
        - '8080:8080'
        depends_on:
        - mongodb
        - redis
        - libretranslate

    frontend:
        build: ./frontend
        ports:
        - '3000:3000'
        depends_on:
        - backend

    mongodb:
        image: mongo:7.0
        volumes:
        - mongodb-data:/data/db

    redis:
        image: redis
        volumes:
        - redis-data:/data

    libretranslate:
        image: libretranslate/libretranslate
        tty: true

volumes:
    mongodb-data:
    redis-data:
